version: '3.8'

services:
  db:
    container_name: "postgres-00"
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messages